####################################################
#                                                  #
#   Author: Muszek                                 #
#   If you need help, join to discord              #
#   server: https://discord.com/invite/cT5MxqAYTd  #
#                                                  #
####################################################

# Type of saving data: 'yaml' or 'mysql'
storage-type: mysql

database:
  host: "localhost"
  port: 3306
  database: "minecraft"
  username: "root"
  password: ""
  table-prefix: "fb_"
  use-ssl: false


settings:
  locale: en
  timezone: Europe/Warsaw
expire-check-interval-seconds: 60
bounty-default-limit: 3

Bounty:
  #Time in minutes
  Time: 1440
  #If there are several bounties on player, should all be completed on kill = true or one by one (false)?
  Stacked: true